# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import pyi2phosts.lib.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=256, validators=[pyi2phosts.lib.validation.validate_i2purl])),
                ('description', models.CharField(blank=True, max_length=512)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
