# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='i2phost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67, unique=True, verbose_name='I2P hostname')),
                ('b64hash', models.CharField(max_length=616, verbose_name='Base 64 hash')),
                ('description', models.CharField(blank=True, max_length=4096, verbose_name='Description')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingHost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('postkey.i2phost',),
        ),
    ]
